plate-stack:
  hosts:
    test-plate-stack.kot-labs.com:
      app_port: 3001
      container_name: test-plate-stack
      container_port: 3000
      publish_ports: "{{ app_port }}:{{ container_port}}"
      base_image: public.ecr.aws/flynshue/plate-stack
      image_version: v0.0.2
      image: "{{ base_image }}:{{ image_version }}"