name: Bump version
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.17

      - name: Install dependencies
        run: go mod tidy

      - name: Run test
        run: go test -v .

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to AWS Public ECR
        uses: docker/login-action@v2.1.0
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Get version
        id: version
        run: |
          version=$(cat VERSION)
          if [[ $(git ls-remote --tags origin | grep $version) ]]; then
              echo "Tag v$version already exists. Please bump VERSION file."
              exit 1
          fi
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Get dry-run mode
        id: dry_run
        run: |
          dry_run=false
          if ${{ github.event_name == 'pull_request' }}; then
          echo "dry_run=true" >> $GITHUB_OUTPUT
          fi

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}
          default_bump: false
          default_prerelease_bump: false
          dry_run: ${{ steps.dry_run.outputs.dry_run }}

      - name: Create a GitHub release
        if: github.event_name == 'push'
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: plate-stack ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --clean
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         GORELEASER_CURRENT_TAG: ${{ steps.tag_version.outputs.new_tag }}

      - name: Push to AWS Public ECR
        if: github.event_name == 'push'
        run: |
          docker push public.ecr.aws/flynshue/plate-stack:${{ steps.tag_version.outputs.new_tag }}
