name: Bump version
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.2

      - name: Install dependencies
        run: go mod tidy

      - name: Run test
        run: go test -v .

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          version=$(cat VERSION)
          if [[ $(git ls-remote --tags origin | grep "refs/tags/v${version}$") ]]; then
              echo "Tag v$version already exists. Please bump VERSION file."
              exit 1
          fi
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Login to AWS Public ECR
        uses: docker/login-action@v4
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}
          default_bump: false
          default_prerelease_bump: false
          dry_run: ${{ github.event_name == 'pull_request' }}

      - name: Setup qemu
        uses: docker/setup-qemu-action@v4

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v4

      - name: set goreleaser args
        id: goreleaser_args
        run: |
          args="release --clean"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            args="$args --snapshot"
          fi
          echo "args=${args}" >> $GITHUB_OUTPUT

      - name: fetch tags
        run: git fetch --tags

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: ${{ steps.goreleaser_args.outputs.args }}
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         GORELEASER_CURRENT_TAG: ${{ steps.tag_version.outputs.new_tag }}

      - name: Push snapshot image to ECR
        if: github.event_name == 'pull_request'
        run: |
          short_sha=$(git rev-parse --short HEAD)
          docker push public.ecr.aws/flynshue/plate-stack:${{ steps.tag_version.outputs.new_tag }}-${short_sha}-amd64
          docker push public.ecr.aws/flynshue/plate-stack:${{ steps.tag_version.outputs.new_tag }}-${short_sha}-arm64
