name: Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.17

      - name: Install dependencies
        run: go mod tidy

      - name: Run test
        run: go test -v .